### ISSUE TITLE
PostgreSQL driver alternative

### ISSUE THREAD

**Issue by vitaly-t** [claytongulick/bit-sync#2]
From your post against `node-postgres`:

> Granted, it's completely my fault I blundered ahead doing it that way instead of investigating a better solution from the start

This usually does pay off :) Try [pg-promise], it has good support of [Named Parameters], among many other things.

Sorry for publishing it here, because if I wrote it there, such posts get deleted, and the author gets banned. That's how friendly and helpful those folks are.

[pg-promise]:https://github.com/vitaly-t/pg-promise
[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters

**Comment by claytongulick** [comment]
Thanks @vitaly-t for the pointer to pg-promise and the great work on it, going to close this issue here since it's not really relevant to this project. Thanks again!
